# .github/labeler.yml
"scripts/**":  ["area:scripts"]
"packages/**": ["area:packages"]
"schema/**":   ["area:schema"]
"*.ps1":       ["lang:powershell"]
".github/**":  ["area:ci"]
"**/*.md":     ["docs"]