-- === api_keys ===
CREATE TABLE IF NOT EXISTS api_keys (
  id               BIGSERIAL PRIMARY KEY,
  tenant_id        BIGINT NOT NULL,
  user_id          BIGINT NULL,
  name             VARCHAR(120) NOT NULL,
  name_ci          TEXT GENERATED ALWAYS AS (lower(name)) STORED,
  token_hash       BYTEA NOT NULL,
  token_hash_key_version VARCHAR(64) NOT NULL,
  scopes           JSONB NOT NULL DEFAULT '[]'::jsonb,
  status           VARCHAR(20) NOT NULL DEFAULT 'active',
  last_used_at     TIMESTAMPTZ(6) NULL,
  expires_at       TIMESTAMPTZ(6) NULL,
  created_at       TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at       TIMESTAMPTZ(6) NULL,
  CONSTRAINT chk_api_keys_status CHECK (status IN ('active','revoked','disabled'))
);

-- === app_settings ===
CREATE TABLE IF NOT EXISTS app_settings (
  setting_key VARCHAR(100) PRIMARY KEY,
  setting_value TEXT NULL,
  "type" TEXT NOT NULL,
  section VARCHAR(100) NULL,
  description TEXT NULL,
  is_protected BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_app_settings_version CHECK (version >= 0),
  updated_by BIGINT NULL,
  CONSTRAINT chk_app_settings_type CHECK ("type" IN ('string','int','bool','json','secret'))
);

-- === audit_chain ===
CREATE TABLE IF NOT EXISTS audit_chain (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  audit_id BIGINT NOT NULL,
  chain_name VARCHAR(100) NOT NULL DEFAULT 'default',
  prev_hash BYTEA NULL,
  hash BYTEA NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_audit_chain UNIQUE (audit_id)
);

-- === audit_log ===
CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name VARCHAR(100) NOT NULL,
  record_id BIGINT NOT NULL,
  changed_by BIGINT NULL,
  change_type TEXT NOT NULL,
  old_value JSONB NULL,
  new_value JSONB NULL,
  changed_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  ip_bin BYTEA NULL,
  user_agent VARCHAR(1024) NULL,
  request_id VARCHAR(100) NULL,
  CONSTRAINT chk_audit_change_type CHECK (change_type IN ('INSERT','UPDATE','DELETE'))
);

-- === auth_events ===
CREATE TABLE IF NOT EXISTS auth_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NULL,
  type TEXT NOT NULL,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  user_agent VARCHAR(1024) NULL,
  occurred_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  meta JSONB NULL,
  meta_email TEXT GENERATED ALWAYS AS (meta ->> 'email') STORED,
  CONSTRAINT chk_auth_type CHECK (type IN ('login_success','login_failure','logout','password_reset','lockout'))
);

-- === authors ===
CREATE TABLE IF NOT EXISTS authors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  slug_ci TEXT GENERATED ALWAYS AS (lower(slug)) STORED,
  bio TEXT NULL,
  photo_url VARCHAR(255) NULL,
  story TEXT NULL,
  books_count INTEGER NOT NULL DEFAULT 0,
  ratings_count INTEGER NOT NULL DEFAULT 0,
  rating_sum INTEGER NOT NULL DEFAULT 0,
  avg_rating NUMERIC(3,2) NULL DEFAULT NULL,
  last_rating_at TIMESTAMPTZ(6) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_authors_version CHECK (version >= 0),
  deleted_at TIMESTAMPTZ(6) NULL,
  is_live BOOLEAN GENERATED ALWAYS AS (deleted_at IS NULL) STORED
);

-- === book_assets ===
CREATE TABLE IF NOT EXISTS book_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  asset_type TEXT NOT NULL,
  filename VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  size_bytes BIGINT NOT NULL,
  storage_path TEXT NULL,
  content_hash VARCHAR(64) NULL,
  download_filename VARCHAR(255) NULL,
  is_encrypted BOOLEAN NOT NULL DEFAULT FALSE,
  encryption_algo VARCHAR(50) NULL,
  encryption_key_enc BYTEA NULL,
  encryption_iv  BYTEA NULL,
  encryption_tag BYTEA NULL,
  encryption_aad BYTEA NULL,
  encryption_meta JSONB NULL,
  key_version VARCHAR(64) NULL,
  key_id BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_asset_type CHECK (asset_type IN ('cover','pdf','epub','mobi','sample','extra'))
);

-- === book_categories ===
CREATE TABLE IF NOT EXISTS book_categories (
  tenant_id  BIGINT NOT NULL,
  book_id    BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  PRIMARY KEY (tenant_id, book_id, category_id)
);

-- === books ===
CREATE TABLE IF NOT EXISTS books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  slug_ci TEXT GENERATED ALWAYS AS (lower(slug)) STORED,
  short_description VARCHAR(512) NULL,
  full_description TEXT NULL,
  price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  currency CHAR(3) NOT NULL DEFAULT 'EUR',
  author_id BIGINT NOT NULL,
  main_category_id BIGINT NOT NULL,
  isbn VARCHAR(32) NULL,
  language CHAR(5) NULL,
  pages INTEGER NULL,
  publisher VARCHAR(255) NULL,
  published_at DATE NULL,
  sku VARCHAR(64) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  stock_quantity INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_books_version CHECK (version >= 0),
  deleted_at TIMESTAMPTZ(6) NULL,
  is_live BOOLEAN GENERATED ALWAYS AS (deleted_at IS NULL) STORED,
  CONSTRAINT chk_books_pages      CHECK (pages IS NULL OR pages >= 0),
  CONSTRAINT chk_books_stock_qty  CHECK (stock_quantity >= 0),
  CONSTRAINT chk_books_currency CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT chk_books_price_nonneg CHECK (price >= 0)
);

-- === cart_items ===
CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  cart_id CHAR(36) NOT NULL,
  book_id BIGINT NOT NULL,
  sku VARCHAR(64) NULL,
  variant JSONB NULL,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  price_snapshot NUMERIC(12,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  meta JSONB NULL,
  CONSTRAINT chk_cart_currency CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT chk_cart_qty CHECK (quantity > 0)
);

-- === carts ===
CREATE TABLE IF NOT EXISTS carts (
  id CHAR(36) PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT NULL,
  note VARCHAR(200) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_carts_version CHECK (version >= 0)
);

-- === categories ===
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  slug_ci TEXT GENERATED ALWAYS AS (lower(slug)) STORED,
  parent_id BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_categories_version CHECK (version >= 0),
  deleted_at TIMESTAMPTZ(6) NULL,
  is_live BOOLEAN GENERATED ALWAYS AS (deleted_at IS NULL) STORED
);

-- === countries ===
CREATE TABLE IF NOT EXISTS countries (
  iso2 CHAR(2) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  CONSTRAINT chk_countries_iso2 CHECK (iso2 ~ '^[A-Z]{2}$')
);

-- === coupon_redemptions ===
CREATE TABLE IF NOT EXISTS coupon_redemptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  coupon_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  redeemed_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  amount_applied NUMERIC(12,2) NOT NULL
);

-- === coupons ===
CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  code VARCHAR(100) NOT NULL,
  code_ci TEXT GENERATED ALWAYS AS (lower(code)) STORED,
  type TEXT NOT NULL,
  value NUMERIC(12,2) NOT NULL,
  currency CHAR(3) NULL,
  starts_at DATE NOT NULL,
  ends_at DATE NULL,
  max_redemptions INTEGER NOT NULL DEFAULT 0,
  min_order_amount NUMERIC(12,2) NULL,
  applies_to JSONB NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_coupon_percent_fixed
    CHECK (
      (type='percent' AND value BETWEEN 0 AND 100 AND currency IS NULL)
      OR
      (type='fixed'   AND value >= 0 AND currency ~ '^[A-Z]{3}$')
    ),
  CONSTRAINT chk_coupons_range
    CHECK (ends_at IS NULL OR ends_at >= starts_at)
);

-- === crypto_algorithms ===
CREATE TABLE IF NOT EXISTS crypto_algorithms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class TEXT NOT NULL,                       -- 'kem' | 'sig' | 'hash' | 'symmetric'
  name  VARCHAR(120) NOT NULL,               -- e.g. 'ML-KEM-768','ML-DSA-2','SHA3-512','AES-256-GCM'
  variant VARCHAR(80) NULL,                  -- e.g. 'hybrid-x25519', 'fips-202'
  variant_norm TEXT GENERATED ALWAYS AS (COALESCE(variant,'')) STORED,
  nist_level SMALLINT NULL,                  -- 1..5 for PQC, NULL for others
  status TEXT NOT NULL DEFAULT 'active',     -- 'active' | 'deprecated' | 'experimental'
  params JSONB NULL,                         -- e.g. { "ct_max_len": 1792, "pubkey_len": 1184 }
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_crypto_algorithms UNIQUE (class, name, variant_norm),
  CONSTRAINT uq_crypto_algorithms_raw UNIQUE (class, name, variant),
  CONSTRAINT chk_ca_class CHECK (class IN ('kem','sig','hash','symmetric')),
  CONSTRAINT chk_ca_status CHECK (status IN ('active','deprecated','experimental'))
);

-- === crypto_keys ===
CREATE TABLE IF NOT EXISTS crypto_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  basename VARCHAR(100) NOT NULL,
  version INTEGER NOT NULL,
  filename VARCHAR(255) NULL,
  file_path VARCHAR(1024) NULL,
  fingerprint CHAR(64) NULL,
  key_meta JSONB NULL,
  key_type TEXT NULL,
  algorithm VARCHAR(64) NULL,
  length_bits SMALLINT NULL,
  origin TEXT NULL,
  "usage" TEXT[] NULL,
  scope VARCHAR(100) NULL,
  status TEXT NOT NULL DEFAULT 'active',
  is_backup_encrypted BOOLEAN NOT NULL DEFAULT FALSE,
  backup_blob BYTEA NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  activated_at TIMESTAMPTZ(6) NULL,
  retired_at TIMESTAMPTZ(6) NULL,
  replaced_by BIGINT NULL,
  notes TEXT NULL,
  CONSTRAINT uq_keys_basename_version UNIQUE (basename, version),
  CONSTRAINT chk_keys_type    CHECK (key_type IS NULL OR key_type IN ('dek','kek','hmac','pepper')),
  CONSTRAINT chk_keys_origin  CHECK (origin IS NULL OR origin IN ('local','kms','imported')),
  CONSTRAINT chk_keys_status  CHECK (status IN ('active','retired','compromised','archived')),
  CONSTRAINT chk_keys_usage   CHECK ("usage" IS NULL OR "usage" <@ ARRAY['encrypt','decrypt','sign','verify','wrap','unwrap'])
);

-- === crypto_standard_aliases ===
CREATE TABLE IF NOT EXISTS crypto_standard_aliases (
  alias VARCHAR(120) PRIMARY KEY,                 -- e.g. 'kyber768','dilithium2','aesgcm256'
  algo_id BIGINT NOT NULL,
  notes TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- === data_retention_policies ===
CREATE TABLE IF NOT EXISTS data_retention_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  field_name   VARCHAR(64) NULL,
  action TEXT NOT NULL,                         -- 'delete','anonymize','hash','truncate'
  keep_for VARCHAR(64) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  notes TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_drp_action CHECK (action IN ('delete','anonymize','hash','truncate')),
  CONSTRAINT uq_drp_entity_scope UNIQUE (entity_table, field_name, action, keep_for)
);

-- === deletion_jobs ===
CREATE TABLE IF NOT EXISTS deletion_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  entity_pk    VARCHAR(64) NOT NULL,
  reason TEXT NULL,
  hard_delete BOOLEAN NOT NULL DEFAULT FALSE,
  scheduled_at TIMESTAMPTZ(6) NULL,
  started_at   TIMESTAMPTZ(6) NULL,
  finished_at  TIMESTAMPTZ(6) NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  error TEXT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_deletion_jobs UNIQUE (entity_table, entity_pk),
  CONSTRAINT chk_dj_status CHECK (status IN ('pending','running','done','failed','cancelled'))
);

-- === device_fingerprints ===
CREATE TABLE IF NOT EXISTS device_fingerprints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NULL,
  fingerprint_hash BYTEA NOT NULL,
  attributes JSONB NULL,
  risk_score SMALLINT NULL,
  first_seen TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_seen  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_ip_hash BYTEA NULL,
  last_ip_key_version VARCHAR(64) NULL,
  CONSTRAINT uq_device_fp UNIQUE (fingerprint_hash),
  CONSTRAINT chk_df_risk CHECK (risk_score IS NULL OR (risk_score BETWEEN 0 AND 100))
);

-- === email_verifications ===
CREATE TABLE IF NOT EXISTS email_verifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token_hash CHAR(64) NULL,
  selector CHAR(12) NOT NULL,
  validator_hash BYTEA NULL,
  key_version VARCHAR(64) NULL,
  expires_at TIMESTAMPTZ(6) NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  used_at TIMESTAMPTZ(6) NULL
);

-- === encrypted_fields ===
CREATE TABLE IF NOT EXISTS encrypted_fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  entity_pk VARCHAR(64) NOT NULL,
  field_name VARCHAR(64) NOT NULL,
  ciphertext BYTEA NOT NULL,
  meta JSONB NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT ux_enc_entity_field UNIQUE (entity_table, entity_pk, field_name)
);

-- === encryption_bindings ===
CREATE TABLE IF NOT EXISTS encryption_bindings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  entity_pk VARCHAR(64) NOT NULL,
  field_name VARCHAR(64) NULL,
  field_name_norm VARCHAR(64) GENERATED ALWAYS AS (COALESCE(field_name,'')) STORED,
  key_wrapper_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_enc_bind UNIQUE (entity_table, entity_pk, field_name_norm),
  CONSTRAINT uq_enc_bind_raw UNIQUE (entity_table, entity_pk, field_name)
);

-- === encryption_events ===
CREATE TABLE IF NOT EXISTS encryption_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  entity_pk VARCHAR(64) NOT NULL,
  field_name VARCHAR(64) NOT NULL,
  op TEXT NOT NULL,
  policy_id BIGINT NULL,
  local_key_version VARCHAR(64) NULL,
  layers JSONB NULL,
  outcome TEXT NOT NULL,
  error_code VARCHAR(64) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_enc_op CHECK (op IN ('encrypt','decrypt','rotate','rehash','unwrap','wrap')),
  CONSTRAINT chk_enc_outcome CHECK (outcome IN ('success','failure'))
);

-- === encryption_policies ===
CREATE TABLE IF NOT EXISTS encryption_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_name VARCHAR(100) NOT NULL UNIQUE,
  mode TEXT NOT NULL,
  layer_selection TEXT NOT NULL DEFAULT 'defined',
  min_layers SMALLINT NOT NULL DEFAULT 1,
  max_layers SMALLINT NOT NULL DEFAULT 3,
  aad_template JSONB NULL,
  notes TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_enc_mode CHECK (mode IN ('local','kms','multi-kms')),
  CONSTRAINT chk_enc_layer_selection CHECK (layer_selection IN ('defined','round_robin','random','hash_mod'))
);

-- === encryption_policy_bindings ===
CREATE TABLE IF NOT EXISTS encryption_policy_bindings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  field_name   VARCHAR(64) NOT NULL,
  policy_id    BIGINT NOT NULL,
  effective_from TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  notes TEXT NULL,
  CONSTRAINT uq_enc_policy_bind UNIQUE (entity_table, field_name, effective_from)
);

-- === entity_external_ids ===
CREATE TABLE IF NOT EXISTS entity_external_ids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  entity_pk    VARCHAR(64) NOT NULL,
  source       VARCHAR(100) NOT NULL,            -- e.g. 'rbac-repo','crm'
  external_id  VARCHAR(200) NOT NULL,
  created_at   TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_entity_external_ids UNIQUE (entity_table, entity_pk, source)
);

-- === event_dlq ===
CREATE TABLE IF NOT EXISTS event_dlq (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source VARCHAR(100) NOT NULL,
  event_key CHAR(36) NULL,
  event JSONB NOT NULL,
  error TEXT NOT NULL,
  retryable BOOLEAN NOT NULL DEFAULT FALSE,
  attempts INTEGER NOT NULL DEFAULT 0,
  first_failed_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_failed_at  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- === event_inbox ===
CREATE TABLE IF NOT EXISTS event_inbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source VARCHAR(100) NOT NULL,
  event_key CHAR(36) NOT NULL,
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT NULL,
  received_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  processed_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT uq_event_inbox_key UNIQUE (source, event_key),
  CONSTRAINT chk_event_inbox_status CHECK (status IN ('pending','processed','failed'))
);

-- === event_outbox ===
CREATE TABLE IF NOT EXISTS event_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key CHAR(36) NOT NULL,
  entity_table VARCHAR(64) NOT NULL,
  entity_pk VARCHAR(64) NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMPTZ(6) NULL,
  processed_at TIMESTAMPTZ(6) NULL,
  producer_node VARCHAR(100) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_event_outbox_key UNIQUE (event_key),
  CONSTRAINT chk_event_outbox_status CHECK (status IN ('pending','sent','failed'))
);

-- === field_hash_policies ===
CREATE TABLE IF NOT EXISTS field_hash_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  field_name   VARCHAR(64) NOT NULL,
  profile_id   BIGINT NOT NULL,               -- hash_profiles
  effective_from TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  notes TEXT NULL,
  CONSTRAINT uq_fhp UNIQUE (entity_table, field_name, effective_from)
);

-- === global_id_registry ===
CREATE TABLE IF NOT EXISTS global_id_registry (
  gid CHAR(26) PRIMARY KEY,                     -- ULID (portable)
  guid UUID NULL,                               -- optionally also UUID
  entity_table VARCHAR(64) NOT NULL,
  entity_pk    VARCHAR(64) NOT NULL,
  created_at   TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_gid_entity UNIQUE (entity_table, entity_pk)
);

-- === hash_profiles ===
CREATE TABLE IF NOT EXISTS hash_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  algo_id BIGINT NOT NULL,                    -- crypto_algorithms (class='hash'), e.g. SHA3-512
  output_len SMALLINT NULL,                   -- in bytes; NULL = full length
  params JSONB NULL,                          -- e.g. { "peppered": true, "context": "email", "domain_sep": "app:v1" }
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_hash_profiles UNIQUE (name),
  CONSTRAINT chk_hp_status CHECK (status IN ('active','deprecated'))
);

-- === idempotency_keys ===
CREATE TABLE IF NOT EXISTS idempotency_keys (
  key_hash CHAR(64) NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  payment_id BIGINT NULL DEFAULT NULL,
  order_id BIGINT NULL DEFAULT NULL,
  gateway_payload JSONB NULL,
  redirect_url VARCHAR(1024) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  ttl_seconds INTEGER NOT NULL DEFAULT 86400
);

-- === inventory_reservations ===
CREATE TABLE IF NOT EXISTS inventory_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  book_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  reserved_until TIMESTAMPTZ(6) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_reservations_version CHECK (version >= 0),
  CONSTRAINT chk_res_qty CHECK (quantity > 0),
  CONSTRAINT chk_res_status CHECK (status IN ('pending','confirmed','expired','cancelled')),
  CONSTRAINT chk_res_until_after_created CHECK (reserved_until > created_at)
);

-- === invoice_items ===
CREATE TABLE IF NOT EXISTS invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  invoice_id BIGINT NOT NULL,
  line_no INTEGER NOT NULL,
  description TEXT NOT NULL,
  unit_price NUMERIC(12,2) NOT NULL,
  quantity INTEGER NOT NULL,
  tax_rate NUMERIC(5,2) NOT NULL,
  tax_amount NUMERIC(12,2) NOT NULL,
  line_total NUMERIC(12,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  CONSTRAINT uq_invoice_line UNIQUE (invoice_id, line_no),
  CONSTRAINT chk_invoice_items_currency CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT chk_invoice_items_qty CHECK (quantity > 0),
  CONSTRAINT chk_invoice_items_nonneg CHECK (unit_price >= 0 AND tax_amount >= 0 AND line_total >= 0)
);

-- === invoices ===
CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  invoice_number VARCHAR(100) NOT NULL,
  variable_symbol VARCHAR(50) NULL,
  issue_date DATE NOT NULL,
  due_date DATE NULL,
  subtotal NUMERIC(12,2) NOT NULL,
  discount_total NUMERIC(12,2) NOT NULL,
  tax_total NUMERIC(12,2) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  qr_data TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_invoices_currency CHECK (currency ~ '^[A-Z]{3}$')
);

-- === jwt_tokens ===
CREATE TABLE IF NOT EXISTS jwt_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jti CHAR(36) NOT NULL UNIQUE,
  user_id BIGINT NULL,
  token_hash BYTEA NOT NULL,
  token_hash_algo VARCHAR(50) NULL,
  token_hash_key_version VARCHAR(64) NULL,
  type TEXT NOT NULL DEFAULT 'refresh',
  scopes VARCHAR(255) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_jwt_tokens_version CHECK (version >= 0),
  expires_at TIMESTAMPTZ(6) NULL,
  last_used_at TIMESTAMPTZ(6) NULL,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  replaced_by BIGINT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  meta JSONB NULL,
  CONSTRAINT uq_jwt_token_hash UNIQUE (token_hash),
  CONSTRAINT chk_jwt_type CHECK (type IN ('refresh','api')),
  CONSTRAINT chk_jwt_expires_after_created CHECK (expires_at IS NULL OR expires_at >= created_at)
);

-- === key_events ===
CREATE TABLE IF NOT EXISTS key_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_id BIGINT NULL,
  basename VARCHAR(100) NULL,
  event_type TEXT NOT NULL,
  actor_id BIGINT NULL,
  job_id BIGINT NULL,
  note TEXT NULL,
  meta JSONB NULL,
  "source" TEXT NOT NULL DEFAULT 'admin',
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_key_events_type CHECK (event_type IN ('created','rotated','activated','retired','compromised','deleted','used_encrypt','used_decrypt','access_failed','backup','restore')),
  CONSTRAINT chk_key_events_source CHECK ("source" IN ('cron','admin','api','manual'))
);

-- === key_rotation_jobs ===
CREATE TABLE IF NOT EXISTS key_rotation_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  basename VARCHAR(100) NOT NULL,
  target_version INTEGER NULL,
  scheduled_at TIMESTAMPTZ(6) NULL,
  started_at TIMESTAMPTZ(6) NULL,
  finished_at TIMESTAMPTZ(6) NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 0,
  executed_by BIGINT NULL,
  result TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_key_rotation_status CHECK (status IN ('pending','running','done','failed','cancelled'))
);

-- === key_usage ===
CREATE TABLE IF NOT EXISTS key_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_id BIGINT NOT NULL,
  usage_date DATE NOT NULL,
  encrypt_count INTEGER NOT NULL DEFAULT 0,
  decrypt_count INTEGER NOT NULL DEFAULT 0,
  verify_count  INTEGER NOT NULL DEFAULT 0,
  last_used_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT chk_key_usage_counts CHECK (
    encrypt_count >= 0 AND decrypt_count >= 0 AND verify_count >= 0
  ),
  CONSTRAINT uq_key_usage_key_date UNIQUE (key_id, usage_date)
);

-- === key_wrapper_layers ===
CREATE TABLE IF NOT EXISTS key_wrapper_layers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_wrapper_id BIGINT NOT NULL,
  layer_no SMALLINT NOT NULL,                -- 1..N layer order
  kms_key_id BIGINT NULL,                    -- optional: reference to a KMS key
  kem_algo_id BIGINT NOT NULL,               -- odkaz na crypto_algorithms (class='kem')
  kem_ciphertext BYTEA NOT NULL,             -- encapsulated key (ready for longer PQC ciphertext)
  encap_pubkey BYTEA NULL,                   -- for hybrid/external KEM as needed
  aad JSONB NULL,                            -- AAD used during wrapping
  meta JSONB NULL,                           -- e.g. { "hybrid_with": "x25519" }
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_kwl UNIQUE (key_wrapper_id, layer_no)
);

-- === key_wrappers ===
CREATE TABLE IF NOT EXISTS key_wrappers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wrapper_uuid CHAR(36) NOT NULL,
  kms1_key_id BIGINT NOT NULL,
  kms2_key_id BIGINT NOT NULL,
  dek_wrap1 BYTEA NOT NULL,
  dek_wrap2 BYTEA NOT NULL,
  crypto_suite JSONB NULL,
  wrap_version INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  rotated_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT uq_key_wrappers_uuid UNIQUE (wrapper_uuid),
  CONSTRAINT chk_kw_status CHECK (status IN ('active','rotated','retired','invalid'))
);

-- === kms_health_checks ===
CREATE TABLE IF NOT EXISTS kms_health_checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NULL,
  kms_key_id  BIGINT NULL,
  status TEXT NOT NULL,                           -- 'up','degraded','down'
  latency_ms INTEGER NULL,
  error TEXT NULL,
  checked_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_kms_hc_status CHECK (status IN ('up','degraded','down'))
);

-- === kms_keys ===
CREATE TABLE IF NOT EXISTS kms_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL,
  external_key_ref VARCHAR(512) NOT NULL,
  purpose TEXT NOT NULL DEFAULT 'wrap',
  algorithm VARCHAR(64) NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_kms_purpose CHECK (purpose IN ('wrap','encrypt','both')),
  CONSTRAINT chk_kms_status  CHECK (status  IN ('active','retired','disabled'))
);

-- === kms_providers ===
CREATE TABLE IF NOT EXISTS kms_providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  provider TEXT NOT NULL,
  location VARCHAR(100) NULL,
  project_tenant VARCHAR(150) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT chk_kms_provider CHECK (provider IN ('gcp','aws','azure','vault'))
);

-- === kms_routing_policies ===
CREATE TABLE IF NOT EXISTS kms_routing_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  priority INTEGER NOT NULL DEFAULT 0,
  strategy TEXT NOT NULL DEFAULT 'prefer',      -- 'prefer','require','avoid'
  match JSONB NULL,                             -- e.g. {"tenant_id":123,"region":"eu"}
  providers JSONB NOT NULL,                     -- e.g. [{"provider_id":1,"weight":80},...]
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_kms_route_strategy CHECK (strategy IN ('prefer','require','avoid'))
);

-- === login_attempts ===
CREATE TABLE IF NOT EXISTS login_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  ip_hash BYTEA NOT NULL,
  attempted_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  success BOOLEAN NOT NULL DEFAULT FALSE,
  user_id BIGINT NULL,
  username_hash BYTEA NULL,
  auth_event_id BIGINT NULL,
  CONSTRAINT chk_login_success CHECK (success IN (FALSE, TRUE))
);

-- === merkle_anchors ===
CREATE TABLE IF NOT EXISTS merkle_anchors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merkle_root_id BIGINT NOT NULL,
  anchor_type TEXT NOT NULL,                   -- 'file','blockchain','notary'
  anchor_ref  VARCHAR(512) NOT NULL,
  anchored_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  meta JSONB NULL,
  CONSTRAINT chk_anchor_type CHECK (anchor_type IN ('file','blockchain','notary')),
  CONSTRAINT uq_merkle_anchor_ref UNIQUE (anchor_ref, anchor_type, merkle_root_id)
);

-- === merkle_roots ===
CREATE TABLE IF NOT EXISTS merkle_roots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_table VARCHAR(64) NOT NULL,
  period_start TIMESTAMPTZ(6) NOT NULL,
  period_end   TIMESTAMPTZ(6) NOT NULL,
  root_hash BYTEA NOT NULL,
  proof_uri VARCHAR(512),
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  leaf_count BIGINT NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_merkle_subject_period UNIQUE (subject_table, period_start, period_end)
);

-- === migration_events ===
CREATE TABLE IF NOT EXISTS migration_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_name VARCHAR(120) NOT NULL,
  from_version VARCHAR(64) NULL,
  to_version   VARCHAR(64) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  started_at   TIMESTAMPTZ(6) NULL,
  finished_at  TIMESTAMPTZ(6) NULL,
  error TEXT NULL,
  meta JSONB NULL,
  CONSTRAINT chk_mig_status CHECK (status IN ('pending','running','done','failed','cancelled'))
);

-- === newsletter_subscribers ===
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT NULL,
  email_hash BYTEA NOT NULL,
  email_hash_key_version VARCHAR(64) NULL,
  email_enc BYTEA NULL,
  email_key_version VARCHAR(64) NULL,
  confirm_selector CHAR(12) DEFAULT NULL,
  confirm_validator_hash BYTEA DEFAULT NULL,
  confirm_key_version VARCHAR(64) DEFAULT NULL,
  confirm_expires TIMESTAMPTZ(6) DEFAULT NULL,
  confirmed_at TIMESTAMPTZ(6) DEFAULT NULL,
  unsubscribe_token_hash BYTEA DEFAULT NULL,
  unsubscribe_token_key_version VARCHAR(64) DEFAULT NULL,
  unsubscribed_at TIMESTAMPTZ(6) DEFAULT NULL,
  origin VARCHAR(100) DEFAULT NULL,
  ip_hash BYTEA DEFAULT NULL,
  ip_hash_key_version VARCHAR(64) DEFAULT NULL,
  meta JSONB DEFAULT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_ns_version CHECK (version >= 0)
);

-- === notifications ===
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT NULL,
  channel TEXT NOT NULL,
  template VARCHAR(100) NOT NULL,
  payload JSONB NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  retries INTEGER NOT NULL DEFAULT 0,
  max_retries INTEGER NOT NULL DEFAULT 6,
  next_attempt_at TIMESTAMPTZ(6) NULL,
  scheduled_at TIMESTAMPTZ(6) NULL,
  sent_at TIMESTAMPTZ(6) NULL,
  error TEXT NULL,
  last_attempt_at TIMESTAMPTZ(6) NULL,
  locked_until TIMESTAMPTZ(6) NULL,
  locked_by VARCHAR(100) NULL,
  priority INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_notifications_version CHECK (version >= 0),
  CONSTRAINT chk_notifications_channel CHECK (channel IN ('email','push')),
  CONSTRAINT chk_notifications_status CHECK (status IN ('pending','processing','sent','failed'))
);

-- === order_item_downloads ===
CREATE TABLE IF NOT EXISTS order_item_downloads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  asset_id BIGINT NOT NULL,
  download_token_hash BYTEA NULL,
  token_key_version VARCHAR(64) NULL,
  key_version VARCHAR(64) NULL,
  max_uses INTEGER NOT NULL,
  used INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN GENERATED ALWAYS AS (used < max_uses) STORED,
  expires_at TIMESTAMPTZ(6) NOT NULL,
  last_used_at TIMESTAMPTZ(6) NULL,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL
);

-- === order_items ===
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  book_id BIGINT NULL,
  product_ref INTEGER NULL,
  title_snapshot VARCHAR(255) NOT NULL,
  sku_snapshot VARCHAR(64) NULL,
  unit_price NUMERIC(12,2) NOT NULL,
  quantity INTEGER NOT NULL,
  tax_rate NUMERIC(5,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  CONSTRAINT chk_order_items_qty CHECK (quantity > 0),
  CONSTRAINT chk_order_items_currency CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT chk_order_items_tax_rate CHECK (tax_rate BETWEEN 0 AND 100),
  CONSTRAINT chk_order_items_nonneg CHECK (unit_price >= 0)
);

-- === orders ===
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  uuid CHAR(36) NOT NULL UNIQUE,
  uuid_bin BYTEA NULL,
  public_order_no VARCHAR(64) NULL,
  user_id BIGINT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  encrypted_customer_blob BYTEA NULL,
  encrypted_customer_blob_key_version VARCHAR(64) NULL,
  encryption_meta JSONB NULL,
  currency CHAR(3) NOT NULL,
  metadata JSONB NULL,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(100) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_orders_version CHECK (version >= 0),
  CONSTRAINT chk_orders_status CHECK (status IN ('pending','paid','failed','cancelled','refunded','completed')),
  CONSTRAINT chk_orders_currency CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT chk_orders_nonneg CHECK (subtotal >= 0 AND discount_total >= 0 AND tax_total >= 0 AND total >= 0),
  CONSTRAINT chk_orders_total_eq CHECK (total = subtotal - discount_total + tax_total)
);

-- === payment_gateway_notifications ===
CREATE TABLE IF NOT EXISTS payment_gateway_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id VARCHAR(255) NOT NULL,
  tenant_id BIGINT NOT NULL,
  received_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_pg_notify_version CHECK (version >= 0),
  processing_by VARCHAR(100) NULL,
  processing_until TIMESTAMPTZ(6) NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error VARCHAR(255) NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  CONSTRAINT chk_pg_notify_status CHECK (status IN ('pending','processing','done','failed')),
  CONSTRAINT chk_pg_notify_attempts CHECK (attempts >= 0)
);

-- === payment_logs ===
CREATE TABLE IF NOT EXISTS payment_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id BIGINT NOT NULL,
  log_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  message TEXT NOT NULL
);

-- === payment_webhooks ===
CREATE TABLE IF NOT EXISTS payment_webhooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id BIGINT NULL,
  gateway_event_id VARCHAR(255) NULL,
  payload_hash CHAR(64) NOT NULL,
  payload JSONB NULL,
  from_cache BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- === payments ===
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  gateway VARCHAR(100) NOT NULL,
  transaction_id VARCHAR(255) NULL,
  provider_event_id VARCHAR(255) NULL,
  status TEXT NOT NULL,
  amount NUMERIC(12,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  details JSONB NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_payments_version CHECK (version >= 0),
  CONSTRAINT chk_payments_status CHECK (status IN ('initiated','pending','authorized','paid','cancelled','partially_refunded','refunded','failed')),
  CONSTRAINT chk_payments_currency CHECK (currency ~ '^[A-Z]{3}$')
);

-- === peer_nodes ===
CREATE TABLE IF NOT EXISTS peer_nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  "type" TEXT NOT NULL,
  location VARCHAR(120) NULL,
  status TEXT NOT NULL DEFAULT 'active',
  last_seen TIMESTAMPTZ(6) NULL,
  meta JSONB NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_peer_type CHECK ("type" IN ('postgres','mysql','app','service')),
  CONSTRAINT chk_peer_status CHECK (status IN ('active','offline','degraded','disabled'))
);

-- === permissions ===
CREATE TABLE IF NOT EXISTS permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- === policy_algorithms ===
CREATE TABLE IF NOT EXISTS policy_algorithms (
  policy_id BIGINT NOT NULL,
  algo_id   BIGINT NOT NULL,
  role TEXT NOT NULL,                        -- 'kem' | 'sig' | 'hash' | 'symmetric'
  weight INTEGER NOT NULL DEFAULT 1,
  priority INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (policy_id, algo_id, role),
  CONSTRAINT chk_pa_role CHECK (role IN ('kem','sig','hash','symmetric'))
);

-- === policy_kms_keys ===
CREATE TABLE IF NOT EXISTS policy_kms_keys (
  policy_id BIGINT NOT NULL,
  kms_key_id BIGINT NOT NULL,
  weight INTEGER NOT NULL DEFAULT 1,
  priority INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (policy_id, kms_key_id)
);

-- === pq_migration_jobs ===
CREATE TABLE IF NOT EXISTS pq_migration_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope TEXT NOT NULL,                         -- 'hashes' | 'wrappers' | 'signatures'
  target_policy_id BIGINT NULL,                -- encryption_policies.id (when switching the policy)
  target_algo_id BIGINT NULL,                  -- crypto_algorithms.id (e.g. ML-KEM-768)
  selection JSONB NULL,                        -- e.g. { "table": "encrypted_fields", "field": "ciphertext" }
  scheduled_at TIMESTAMPTZ(6) NULL,
  started_at   TIMESTAMPTZ(6) NULL,
  finished_at  TIMESTAMPTZ(6) NULL,
  status TEXT NOT NULL DEFAULT 'pending',      -- 'pending','running','done','failed','cancelled'
  processed_count BIGINT NOT NULL DEFAULT 0,
  error TEXT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_pq_mig_status CHECK (status IN ('pending','running','done','failed','cancelled'))
);

-- === privacy_requests ===
CREATE TABLE IF NOT EXISTS privacy_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NULL,
  "type" TEXT NOT NULL,                         -- 'access','erasure','rectify','restrict','portability'
  status TEXT NOT NULL DEFAULT 'pending',
  requested_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  processed_at TIMESTAMPTZ(6) NULL,
  meta JSONB NULL,
  CONSTRAINT chk_pr_type CHECK ("type" IN ('access','erasure','rectify','restrict','portability')),
  CONSTRAINT chk_pr_status CHECK (status IN ('pending','processing','done','failed','cancelled'))
);

-- === rate_limit_counters ===
CREATE TABLE IF NOT EXISTS rate_limit_counters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_type TEXT NOT NULL,
  subject_id   VARCHAR(128) NOT NULL,
  name         VARCHAR(120) NOT NULL,
  window_start TIMESTAMPTZ(6) NOT NULL,
  window_size_sec INTEGER NOT NULL,
  "count" INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_rlc UNIQUE (subject_type, subject_id, name, window_start, window_size_sec)
);

-- === rate_limits ===
CREATE TABLE IF NOT EXISTS rate_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_type TEXT NOT NULL,                   -- 'ip','user','api_key','tenant'
  subject_id   VARCHAR(128) NOT NULL,
  name         VARCHAR(120) NOT NULL,          -- e.g. 'login','api'
  window_size_sec INTEGER NOT NULL,
  limit_count    INTEGER NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_rate_limits UNIQUE (subject_type, subject_id, name, window_size_sec),
  CONSTRAINT chk_rate_window CHECK (window_size_sec > 0),
  CONSTRAINT chk_rate_limit  CHECK (limit_count  > 0)
);

-- === rbac_repo_snapshots ===
CREATE TABLE IF NOT EXISTS rbac_repo_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repo_id BIGINT NOT NULL,
  commit_id VARCHAR(128) NOT NULL,
  taken_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  metadata JSONB NULL,
  CONSTRAINT uq_rbac_repo_snap UNIQUE (repo_id, commit_id)
);

-- === rbac_repositories ===
CREATE TABLE IF NOT EXISTS rbac_repositories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  url  VARCHAR(1024) NULL,
  signing_key_id BIGINT NULL,                      -- optional: verify snapshot signatures
  status TEXT NOT NULL DEFAULT 'active',           -- 'active','disabled'
  last_synced_at TIMESTAMPTZ(6) NULL,
  last_commit VARCHAR(128) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- === rbac_role_permissions ===
CREATE TABLE IF NOT EXISTS rbac_role_permissions (
  role_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  effect TEXT NOT NULL DEFAULT 'allow',           -- 'allow' | 'deny'
  source TEXT NOT NULL DEFAULT 'repo',            -- 'repo' | 'local'
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (role_id, permission_id),
  CONSTRAINT chk_rbac_role_perm_effect CHECK (effect IN ('allow','deny')),
  CONSTRAINT chk_rbac_role_perm_source CHECK (source IN ('repo','local'))
);

-- === rbac_roles ===
CREATE TABLE IF NOT EXISTS rbac_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repo_id BIGINT NULL,
  slug VARCHAR(120) NOT NULL,                      -- stable role identifier
  name VARCHAR(200) NOT NULL,
  description TEXT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  status  TEXT NOT NULL DEFAULT 'active',          -- 'active','deprecated','archived'
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_rbac_roles_repo_slug UNIQUE (repo_id, slug),
  CONSTRAINT chk_rbac_roles_status CHECK (status IN ('active','deprecated','archived'))
);

-- === rbac_sync_cursors ===
CREATE TABLE IF NOT EXISTS rbac_sync_cursors (
  repo_id BIGINT NOT NULL,
  peer VARCHAR(120) NOT NULL,                    -- consumer identifier (application/DB)
  last_commit VARCHAR(128) NULL,
  last_synced_at TIMESTAMPTZ(6) NULL,
  PRIMARY KEY (repo_id, peer)
);

-- === rbac_user_permissions ===
CREATE TABLE IF NOT EXISTS rbac_user_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  tenant_id BIGINT NULL,
  scope VARCHAR(120) NULL,
  effect TEXT NOT NULL DEFAULT 'allow',           -- 'allow' | 'deny'
  granted_by BIGINT NULL,
  granted_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expires_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT uq_rbac_user_perm UNIQUE (user_id, permission_id, tenant_id, scope),
  CONSTRAINT chk_rbac_user_perm_effect CHECK (effect IN ('allow','deny'))
);

-- === rbac_user_roles ===
CREATE TABLE IF NOT EXISTS rbac_user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  tenant_id BIGINT NULL,                          -- optional multitenant scope
  scope VARCHAR(120) NULL,                        -- e.g. 'project:123'
  status TEXT NOT NULL DEFAULT 'active',          -- 'active','revoked','expired'
  granted_by BIGINT NULL,
  granted_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expires_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT uq_rbac_user_roles UNIQUE (user_id, role_id, tenant_id, scope),
  CONSTRAINT chk_rbac_user_roles_status CHECK (status IN ('active','revoked','expired'))
);

-- === refunds ===
CREATE TABLE IF NOT EXISTS refunds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  payment_id BIGINT NOT NULL,
  amount NUMERIC(12,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  reason TEXT NULL,
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  details JSONB NULL,
  CONSTRAINT chk_refunds_currency CHECK (currency ~ '^[A-Z]{3}$')
);

-- === register_events ===
CREATE TABLE IF NOT EXISTS register_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NULL,
  type TEXT NOT NULL,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  user_agent VARCHAR(1024) NULL,
  occurred_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  meta JSONB NULL,
  CONSTRAINT chk_register_type CHECK (type IN ('register_success','register_failure'))
);

-- === replication_lag_samples ===
CREATE TABLE IF NOT EXISTS replication_lag_samples (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  peer_id BIGINT NOT NULL,
  metric TEXT NOT NULL,                         -- 'apply_lag_ms','transport_lag_ms'
  value BIGINT NOT NULL,
  captured_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_lag_metric CHECK (metric IN ('apply_lag_ms','transport_lag_ms'))
);

-- === retention_enforcement_jobs ===
CREATE TABLE IF NOT EXISTS retention_enforcement_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_id BIGINT NOT NULL,
  scheduled_at TIMESTAMPTZ(6) NULL,
  started_at   TIMESTAMPTZ(6) NULL,
  finished_at  TIMESTAMPTZ(6) NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  processed_count BIGINT NOT NULL DEFAULT 0,
  error TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_rej_status CHECK (status IN ('pending','running','done','failed','cancelled'))
);

-- === reviews ===
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  user_id BIGINT NULL,
  rating SMALLINT NOT NULL,
  review_text TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

-- === rewrap_jobs ===
CREATE TABLE IF NOT EXISTS rewrap_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_wrapper_id BIGINT NOT NULL,
  target_kms1_key_id BIGINT NULL,
  target_kms2_key_id BIGINT NULL,
  scheduled_at TIMESTAMPTZ(6) NULL,
  started_at   TIMESTAMPTZ(6) NULL,
  finished_at  TIMESTAMPTZ(6) NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_rewrap_status CHECK (status IN ('pending','running','done','failed')),
  CONSTRAINT chk_rewrap_attempts CHECK (attempts >= 0)
);

-- === session_audit ===
CREATE TABLE IF NOT EXISTS session_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_token_hash BYTEA NULL,
  session_token_key_version VARCHAR(64) NULL,
  csrf_token_hash BYTEA NULL,
  csrf_key_version VARCHAR(64) NULL,
  session_id VARCHAR(128) NULL,
  event VARCHAR(64) NOT NULL,
  user_id BIGINT NULL,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  user_agent VARCHAR(1024) NULL,
  meta_json JSONB NULL,
  outcome VARCHAR(32) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- === sessions ===
CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash BYTEA NOT NULL,
  token_hash_key_version VARCHAR(64) NULL,
  token_fingerprint BYTEA NULL,
  token_issued_at TIMESTAMPTZ(6) NULL,
  user_id BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_sessions_version CHECK (version >= 0),
  last_seen_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expires_at TIMESTAMPTZ(6) NULL,
  failed_decrypt_count INTEGER NOT NULL DEFAULT 0,
  last_failed_decrypt_at TIMESTAMPTZ(6) NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  user_agent VARCHAR(1024) NULL,
  session_blob BYTEA NULL,
  CONSTRAINT uq_sessions_token_hash UNIQUE (token_hash),
  CONSTRAINT chk_sessions_failed_decrypt_count CHECK (failed_decrypt_count >= 0),
  CONSTRAINT chk_sessions_expires_after_created CHECK (expires_at IS NULL OR expires_at >= created_at)
);

-- === schema_registry ===
CREATE TABLE IF NOT EXISTS schema_registry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_name VARCHAR(120) NOT NULL,
  component   VARCHAR(120) NOT NULL,           -- 'db','rbac','api',...
  version     VARCHAR(64) NOT NULL,
  checksum    VARCHAR(64) NULL,
  applied_at  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  meta JSONB NULL,
  CONSTRAINT uq_schema_version UNIQUE (system_name, component, version)
);

-- === signatures ===
CREATE TABLE IF NOT EXISTS signatures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_table VARCHAR(64) NOT NULL,
  subject_pk    VARCHAR(64) NOT NULL,
  context       VARCHAR(64) NOT NULL,          -- e.g. 'audit_chain','event_outbox','asset'
  algo_id BIGINT NOT NULL,                     -- crypto_algorithms (class='sig')
  signing_key_id BIGINT NULL,                  -- identifies where the signature originates
  signature BYTEA NOT NULL,
  payload_hash BYTEA NOT NULL,                 -- e.g. SHA3-512 hash of the signed payload
  hash_algo_id BIGINT NOT NULL,                -- crypto_algorithms (class='hash')
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_signatures UNIQUE (subject_table, subject_pk, context, algo_id)
);

-- === signing_keys ===
CREATE TABLE IF NOT EXISTS signing_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  algo_id BIGINT NOT NULL,                   -- crypto_algorithms (class='sig')
  name VARCHAR(120) NOT NULL,
  public_key BYTEA NOT NULL,
  private_key_enc BYTEA NULL,                -- when stored encrypted locally
  kms_key_id BIGINT NULL,                    -- when stored in KMS/HSM
  origin TEXT NOT NULL DEFAULT 'local',      -- 'local' | 'kms' | 'imported'
  status TEXT NOT NULL DEFAULT 'active',     -- 'active' | 'retired' | 'compromised'
  scope VARCHAR(120) NULL,                   -- e.g. 'audit', 'events', 'assets'
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  activated_at TIMESTAMPTZ(6) NULL,
  retired_at   TIMESTAMPTZ(6) NULL,
  notes TEXT NULL,
  CONSTRAINT uq_signing_keys_name UNIQUE (name),
  CONSTRAINT chk_sk_origin CHECK (origin IN ('local','kms','imported')),
  CONSTRAINT chk_sk_status CHECK (status IN ('active','retired','compromised'))
);

-- === slo_status ===
CREATE TABLE IF NOT EXISTS slo_status (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_id BIGINT NOT NULL,
  computed_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  sli_value NUMERIC(18,6) NULL,
  good_events BIGINT NOT NULL DEFAULT 0,
  total_events BIGINT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'unknown',       -- 'good','breach','unknown'
  CONSTRAINT uq_slo_status_window UNIQUE (window_id, computed_at),
  CONSTRAINT chk_slo_status CHECK (status IN ('good','breach','unknown'))
);

-- === slo_windows ===
CREATE TABLE IF NOT EXISTS slo_windows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  objective JSONB NOT NULL,                     -- {"metric":"outbox_latency_sec","threshold":10,"percentile":95}
  target_pct NUMERIC(5,2) NOT NULL,
  window_interval INTERVAL NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- === sync_batch_items ===
CREATE TABLE IF NOT EXISTS sync_batch_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL,
  event_key CHAR(36) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  error TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_sync_batch_event UNIQUE (batch_id, event_key),
  CONSTRAINT chk_sbi_status CHECK (status IN ('pending','sent','applied','failed','skipped'))
);

-- === sync_batches ===
CREATE TABLE IF NOT EXISTS sync_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel VARCHAR(120) NOT NULL,
  producer_peer_id BIGINT NOT NULL,
  consumer_peer_id BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  items_total INTEGER NOT NULL DEFAULT 0,
  items_ok    INTEGER NOT NULL DEFAULT 0,
  items_failed INTEGER NOT NULL DEFAULT 0,
  error TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  started_at  TIMESTAMPTZ(6) NULL,
  finished_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT chk_sync_batches_status CHECK (status IN ('pending','sending','completed','failed','cancelled'))
);

-- === sync_errors ===
CREATE TABLE IF NOT EXISTS sync_errors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source VARCHAR(100) NOT NULL,
  event_key CHAR(36) NULL,
  peer_id BIGINT NULL,
  error TEXT NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- === system_errors ===
CREATE TABLE IF NOT EXISTS system_errors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level TEXT NOT NULL,
  message TEXT NOT NULL,
  exception_class VARCHAR(255) NULL,
  file VARCHAR(1024) NULL,
  line INTEGER NULL,
  stack_trace TEXT NULL,
  token VARCHAR(255) NULL,
  context JSONB NULL,
  fingerprint VARCHAR(64) NULL,
  occurrences INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT chk_system_errors_occurrences CHECK (occurrences >= 0),
  user_id BIGINT NULL,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  ip_text VARCHAR(45) NULL,
  ip_bin BYTEA NULL,
  user_agent VARCHAR(1024) NULL,
  url VARCHAR(2048) NULL,
  method VARCHAR(10) NULL,
  http_status SMALLINT NULL,
  resolved BOOLEAN NOT NULL DEFAULT FALSE,
  resolved_by BIGINT NULL,
  resolved_at TIMESTAMPTZ(6) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_seen TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_err_level CHECK (level IN ('notice','warning','error','critical')),
  CONSTRAINT uq_err_fp UNIQUE (fingerprint),
  CONSTRAINT chk_system_errors_http_status CHECK (http_status IS NULL OR http_status >= 0)
);

-- === system_jobs ===
CREATE TABLE IF NOT EXISTS system_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_type VARCHAR(100) NOT NULL,
  payload JSONB NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  retries INTEGER NOT NULL DEFAULT 0,
  scheduled_at TIMESTAMPTZ(6) NULL,
  started_at TIMESTAMPTZ(6) NULL,
  finished_at TIMESTAMPTZ(6) NULL,
  error TEXT NULL,
  unique_key_hash CHAR(64) NULL,
  unique_key_version VARCHAR(64) NULL,
  locked_until TIMESTAMPTZ(6) NULL,
  locked_by VARCHAR(100) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_system_jobs_version CHECK (version >= 0),
  CONSTRAINT chk_system_jobs_status CHECK (status IN ('pending','processing','done','failed')),
  CONSTRAINT chk_system_jobs_retries CHECK (retries >= 0)
);

-- === tax_rates ===
CREATE TABLE IF NOT EXISTS tax_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_iso2 CHAR(2) NOT NULL,
  category TEXT NOT NULL,
  rate NUMERIC(5,2) NOT NULL,
  valid_from DATE NOT NULL,
  valid_to DATE NULL,
  CONSTRAINT chk_tax_category CHECK (category IN ('ebook','physical')),
  CONSTRAINT chk_tax_valid_span CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- === tenant_domains ===
CREATE TABLE IF NOT EXISTS tenant_domains (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  domain VARCHAR(255) NOT NULL,
  domain_ci TEXT GENERATED ALWAYS AS (lower(domain)) STORED,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_tenant_domains UNIQUE (tenant_id, domain_ci)
);

-- === tenants ===
CREATE TABLE IF NOT EXISTS tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  slug VARCHAR(200) NOT NULL,
  slug_ci TEXT GENERATED ALWAYS AS (lower(slug)) STORED,
  status TEXT NOT NULL DEFAULT 'active',              -- 'active','suspended','deleted'
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_tenants_status CHECK (status IN ('active','suspended','deleted')),
  deleted_at TIMESTAMPTZ(6) NULL,
  is_live BOOLEAN GENERATED ALWAYS AS (deleted_at IS NULL) STORED
);

-- === two_factor ===
CREATE TABLE IF NOT EXISTS two_factor (
  user_id BIGINT NOT NULL,
  method VARCHAR(50) NOT NULL,
  secret BYTEA NULL,
  recovery_codes_enc BYTEA NULL,
  hotp_counter BIGINT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_two_factor_version CHECK (version >= 0),
  last_used_at TIMESTAMPTZ(6) NULL,
  PRIMARY KEY (user_id, method),
  CONSTRAINT chk_two_factor_hotp_counter CHECK (hotp_counter IS NULL OR hotp_counter >= 0),
  CONSTRAINT chk_two_factor_method CHECK (method IN ('totp','hotp','webauthn','sms','email'))
);

-- === user_consents ===
CREATE TABLE IF NOT EXISTS user_consents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  consent_type VARCHAR(50) NOT NULL,
  version VARCHAR(50) NOT NULL,
  granted BOOLEAN NOT NULL,
  granted_at TIMESTAMPTZ(6) NOT NULL,
  source VARCHAR(100) NULL,
  meta JSONB NULL
);

-- === user_identities ===
CREATE TABLE IF NOT EXISTS user_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  provider VARCHAR(100) NOT NULL,
  provider_user_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- === user_profiles ===
CREATE TABLE IF NOT EXISTS user_profiles (
  user_id BIGINT PRIMARY KEY,
  profile_enc BYTEA NULL,
  key_version VARCHAR(64) NULL,
  encryption_meta JSONB NULL,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_user_profiles_version CHECK (version >= 0)
);

-- === users ===
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_hash BYTEA NULL,
  email_hash_key_version VARCHAR(64) NULL,
  password_hash VARCHAR(255) NOT NULL,
  password_algo VARCHAR(64) NULL,
  password_key_version VARCHAR(64) NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  is_locked  BOOLEAN NOT NULL DEFAULT FALSE,
  failed_logins INTEGER NOT NULL DEFAULT 0,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  last_login_at TIMESTAMPTZ(6) NULL,
  last_login_ip_hash BYTEA NULL,
  last_login_ip_key_version VARCHAR(64) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_users_version CHECK (version >= 0),
  deleted_at TIMESTAMPTZ(6) NULL,
  actor_role TEXT NOT NULL DEFAULT 'customer',
  CONSTRAINT chk_users_actor_role CHECK (actor_role IN ('customer','admin'))
);

-- === vat_validations ===
CREATE TABLE IF NOT EXISTS vat_validations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vat_id VARCHAR(50) NOT NULL,
  country_iso2 CHAR(2) NOT NULL,
  valid BOOLEAN NOT NULL,
  checked_at TIMESTAMPTZ(6) NOT NULL,
  raw JSONB NULL
);

-- === verify_events ===
CREATE TABLE IF NOT EXISTS verify_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NULL,
  type TEXT NOT NULL,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  user_agent VARCHAR(1024) NULL,
  occurred_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  meta JSONB NULL,
  CONSTRAINT chk_verify_type CHECK (type IN ('verify_success','verify_failure'))
);

-- === webhook_outbox ===
CREATE TABLE IF NOT EXISTS webhook_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(100) NOT NULL,
  payload JSONB NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  retries INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMPTZ(6) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_webhook_outbox_version CHECK (version >= 0),
  CONSTRAINT chk_webhook_status CHECK (status IN ('pending','sent','failed'))
);

-- === worker_locks ===
CREATE TABLE IF NOT EXISTS worker_locks (
  name VARCHAR(191) NOT NULL PRIMARY KEY,
  locked_until TIMESTAMPTZ(6) NOT NULL
);


